# Generated by Django 4.1.4 on 2023-01-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.profil'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Nouveau contract', 'Nouveau contract'), ('Contract en cour', 'Contract en cour'), ('Contract validé', 'Contract validé')], max_length=20, unique=True),
        ),
    ]
