# Generated by Django 4.1.4 on 2023-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[(1, 'commercial'), (2, 'support')], max_length=20),
        ),
    ]
