# Generated by Django 4.1.4 on 2023-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_usertype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Nouveau contract', 'Nouveau contract'), ('Contract en cour', 'Contract en cour'), ('Contract validé', 'Contract validé')], default='Nouveau contract', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'commercial'), (2, 'support')]),
        ),
    ]
