# Generated by Django 4.1.4 on 2023-02-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_eventstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Nouveau contract', 'Nouveau contract'), ('Contract en cour', 'Contract en cour'), ('Contract validé', 'Contract validé')], max_length=20),
        ),
    ]
