# Generated by Django 4.1.4 on 2023-02-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_client_sales_contact'),
    ]

    operations = [
    ]
