# Generated by Django 4.1.4 on 2023-02-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_event_status_alter_eventstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.profil'),
        ),
    ]
