# Generated by Django 4.1.4 on 2023-02-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20230206_1658'),
    ]

    operations = [
    ]
