# Generated by Django 4.1.4 on 2023-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20230206_1725'),
    ]

    operations = [
    ]
