# Generated by Django 4.1.4 on 2023-02-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20230206_1729'),
    ]

    operations = [
    ]
