# Generated by Django 4.1.4 on 2023-02-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_client_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('COMMERCIAL', 'commercial'), ('SUPPORT', 'support')]),
        ),
    ]
