# Generated by Django 4.1.4 on 2023-02-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_usertype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'commercial'), (2, 'support')]),
        ),
    ]
